#!/bin/bash
/usr/bin/aws s3 sync s3://linuxsuperhero_code43435 /var/www/html/
/bin/touch /va/spool/cron/root
sudo /bin/echo '*/5 * * * * aws s3 sync s3://linuxsuperhero_code43435 /var/www/html/' >> /var/spool/cron/root
